apiKey = "YOUR_API_KEY"
baseURL = "https://api.groq.com/"
temperature = 1 # between 0 and 2
model = "llama-3.1-70b-versatile" # any supported model
output = "output.txt" # will overwrite a file with the same name
tokenUsage = false # can be true or false